<%
REM =========================================================================
REM  /Constants.inc
REM -------------------------------------------------------------------------
REM Nome     : Constates do sistema Entregas
REM Descricao: Menu para o Sistema Entregas
REM Home     : http://www.hipertools.com.br/
REM Criacao  : 4/21/0 9:33PM
REM Autor    : Zevallos Tecnologia em Informacao
REM Versao   : 2.0.0.0
REM Local    : Brasília - DF
REM Companhia: 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

  Const conOptionCreateAll    = "0"
  Const conOptionIndices      = "1"
  Const conOptionValores      = "2"
  Const conOptionProdutos     = "3"
  Const conOptionFuncoes      = "4"
  Const conOptionFuncionarios = "5"
  Const conOptionClientes     = "6"
  Const conOptionFornecedores = "7"

  ' Constantes do sistema
  Const conAspas             = """"
  Const conScriptTimeout     = 15
  Const conSessionTimeout    = 300
  Const conConnectionTimeout = 300
  Const conCommandTimeout    = 300
  Const conOptions           = "O"

REM -------------------------------------------------------------------------
REM Fim do Constants.inc
REM =========================================================================
%>