<%
REM -------------------------------------------------------------------------
REM  /HiperTools/Connection.inc
REM -------------------------------------------------------------------------
REM  Descricao  : Constantes do HiperTools30.Connection
REM  Criação    : 19/02/2000 11:21AM
REM  Local      : Brasilia/DF
REM  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
REM               Fernando Aquino <fernando@zevallos.com.br>
REM               Kelson Medeiros <kelson@zevallos.com.br>
REM               Ueslei Silva <ueslei@zevallos.com.br>
REM               Eduardo Silva <ueslei@zevallos.com.br>
REM               Ridai Govinda <ridai@zevallos.com.br>
REM  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

REM ConnectionType
REM ------------------------------------------------------
Const conConnSQL     = 1
Const conConnDBase   = 2
Const conConnAccess  = 3
Const conConnExcel   = 4
Const conConnFoxPro  = 5
Const conConnText    = 6
Const conConnParadox = 7


REM DriverID
REM ------------------------------------------------------
Const conConnDriverAccess   = 25
Const conConnDriverdBaseIII = 21
Const conConnDriverdBaseIV  = 277
Const conConnDriverdBase5   = 533
Const conConnDriverExcel3   = 534
Const conConnDriverExcel4   = 278
Const conConnDriverExcel7   = 22
Const conConnDriverExcel5   = 22
Const conConnDriverExcel97  = 790
Const conConnDriverFoxPro20 = 24
Const conConnDriverFoxPro25 = 280
Const conConnDriverFoxPro26 = 536
Const conConnDriverParadox3 = 26
Const conConnDriverParadox4 = 282
Const conConnDriverParadox5 = 538
Const conConnDriverText     = 27

%>