<%
// -------------------------------------------------------------------------
//  /HiperTools/Connection.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30.Connection
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

// ConnectionType
// ------------------------------------------------------
var conConnSQL     = 1;
var conConnDBase   = 2;
var conConnAccess  = 3;
var conConnExcel   = 4;
var conConnFoxPro  = 5;
var conConnText    = 6;
var conConnParadox = 7;

// DriverID
// ------------------------------------------------------
var conConnDriverAccess   = 25;
var conConnDriverdBaseIII = 21;
var conConnDriverdBaseIV  = 277;
var conConnDriverdBase5   = 533;
var conConnDriverExcel3   = 534;
var conConnDriverExcel4   = 278;
var conConnDriverExcel7   = 22;
var conConnDriverExcel5   = 22;
var conConnDriverExcel97  = 790;
var conConnDriverFoxPro20 = 24;
var conConnDriverFoxPro25 = 280;
var conConnDriverFoxPro26 = 536;
var conConnDriverParadox3 = 26;
var conConnDriverParadox4 = 282;
var conConnDriverParadox5 = 538;
var conConnDriverText     = 27;

%>