<%
REM -------------------------------------------------------------------------
REM  /HiperTools/HiperTools30.inc
REM -------------------------------------------------------------------------
REM  Descricao  : Constantes do HiperTools30
REM  Criação    : 19/02/2000 11:21AM
REM  Local      : Brasilia/DF
REM  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
REM               Fernando Aquino <fernando@zevallos.com.br>
REM               Kelson Medeiros <kelson@zevallos.com.br>
REM               Ueslei Silva <ueslei@zevallos.com.br>
REM               Eduardo Silva <ueslei@zevallos.com.br>
REM               José Neiva <neiva@zevallos.com.br>
REM               Ridai Govinda <ridai@zevallos.com.br>
REM  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

Option Explicit

%>
<!--#INCLUDE VIRTUAL="/HiperTools/AdoVbs.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/Registry.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/String.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/EditForm.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/Connection.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/Table.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/Show.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/Validate.inc"-->
