<%
// -------------------------------------------------------------------------
//  /HiperTools/HiperTools30.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               José Neiva <neiva@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

%>
<!--#INCLUDE VIRTUAL="/HiperTools/adojavas.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/RegistryJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/StringJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/EditFormJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/ConnectionJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/TableJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/ShowJS.inc"-->
<!--#INCLUDE VIRTUAL="/HiperTools/ValidateJS.inc"-->
