<%

  var Browse;
  var DataBase;
  var Default;
  var Edit;
  var Form;
  var Initializer;
  var Pack;
  var Show;
  var Strings;
  var Table;
  var URL;
  var Validate;
  var TreeView;
  var Registry;

  Initializer = Server.CreateObject("HiperTools30.Initializer");
  Browse      = Server.CreateObject("HiperTools30.Browse");
  DataBase    = Server.CreateObject("HiperTools30.DataBase");
  Default     = Server.CreateObject("HiperTools30.Default");
  Edit        = Server.CreateObject("HiperTools30.EditForm");
  Form        = Server.CreateObject("HiperTools30.Form");
  Pack        = Server.CreateObject("HiperTools30.Pack");
  Show        = Server.CreateObject("HiperTools30.Show");
  Strings     = Server.CreateObject("HiperTools30.String");
  Table       = Server.CreateObject("HiperTools30.Table");
  URL         = Server.CreateObject("HiperTools30.URL");
  Validate    = Server.CreateObject("HiperTools30.Validate");
  TreeView    = Server.CreateObject("HiperTools30.TreeView");
  Registry    = Server.CreateObject("HiperTools30.Registry");
%>