<%

  Public Browse
  Public DataBase
  Public Default
  Public Edit
  Public Form
  Public Initializer
  Public Pack
  Public Show
  Public Strings
  Public Table
  Public URL
  Public Validate
  Public TreeView

  Set Initializer = Server.CreateObject("HiperTools30.Initializer")
  Set Browse      = Server.CreateObject("HiperTools30.Browse")
  Set DataBase    = Server.CreateObject("HiperTools30.DataBase")
  Set Default     = Server.CreateObject("HiperTools30.Default")
  Set Edit        = Server.CreateObject("HiperTools30.EditForm")
  Set Form        = Server.CreateObject("HiperTools30.Form")
  Set Pack        = Server.CreateObject("HiperTools30.Pack")
  Set Show        = Server.CreateObject("HiperTools30.Show")
  Set Strings     = Server.CreateObject("HiperTools30.String")
  Set Table       = Server.CreateObject("HiperTools30.Table")
  Set URL         = Server.CreateObject("HiperTools30.URL")
  Set Validate    = Server.CreateObject("HiperTools30.Validate")
  Set TreeView    = Server.CreateObject("HiperTools30.TreeView")
%>