<%
// -------------------------------------------------------------------------
//  /HiperTools/Show.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30.Show
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//               Flavio Costa <flavio@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

// ItemListBegin Parameters
// ------------------------------------------------------
var shListTypeDisc = 1;
var shListTypeCircle = 2;
var shListTypeSquare = 3;
var shListTypeNumber = 4;
var shListTypeUChar = 5;
var shListTypeLChar = 6;
var shListTypeURoman = 7;
var shListTypeLRoman = 8;

%>