<%
REM -------------------------------------------------------------------------
REM  /HiperTools/Show.inc
REM -------------------------------------------------------------------------
REM  Descricao  : Constantes do HiperTools30.Show
REM  Criação    : 19/02/2000 11:21AM
REM  Local      : Brasilia/DF
REM  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
REM               Fernando Aquino <fernando@zevallos.com.br>
REM               Kelson Medeiros <kelson@zevallos.com.br>
REM               Ueslei Silva <ueslei@zevallos.com.br>
REM               Eduardo Silva <ueslei@zevallos.com.br>
REM               Ridai Govinda <ridai@zevallos.com.br>
REM               Flavio Costa <flavio@zevallos.com.br>
REM  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

REM ItemListBegin Parameters
REM ------------------------------------------------------
Const shListTypeDisc = 1
Const shListTypeCircle = 2
Const shListTypeSquare = 3
Const shListTypeNumber = 4
Const shListTypeUChar = 5
Const shListTypeLChar = 6
Const shListTypeURoman = 7
Const shListTypeLRoman = 8

%>