<%
// -------------------------------------------------------------------------
//  /HiperTools/String.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30.String
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

// ImportDate Parameters
// --------------------------
var stDateTypeAAMMDD = 0;
var stDateTypeAAAAMMDD = 1;
var stDateTypeMMDDAA = 2;
var stDateTypeMMDDAAAA = 3;
var stDateTypeDDMMAA = 4;
var stDateTypeDDMMAAAA = 5

// ImportMoney Parameters
// --------------------------
var stMoneyType9999D99 = 0;
var stMoneyType9D999D99 = 1;
var stMoneyType9999 = 2;
%>