<%
REM -------------------------------------------------------------------------
REM  /HiperTools/String.inc
REM -------------------------------------------------------------------------
REM  Descricao  : Constantes do HiperTools30.String
REM  Criação    : 19/02/2000 11:21AM
REM  Local      : Brasilia/DF
REM  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
REM               Fernando Aquino <fernando@zevallos.com.br>
REM               Kelson Medeiros <kelson@zevallos.com.br>
REM               Ueslei Silva <ueslei@zevallos.com.br>
REM               Eduardo Silva <ueslei@zevallos.com.br>
REM               Ridai Govinda <ridai@zevallos.com.br>
REM  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

REM ImportDate Parameters
REM --------------------------
Const stDateTypeAAMMDD = 0
Const stDateTypeAAAAMMDD = 1
Const stDateTypeMMDDAA = 2
Const stDateTypeMMDDAAAA = 3
Const stDateTypeDDMMAA = 4
Const stDateTypeDDMMAAAA = 5

REM ImportMoney Parameters
REM --------------------------
Const stMoneyType9999D99 = 0
Const stMoneyType9D999D99 = 1
Const stMoneyType9999 = 2
%>