<%
// -------------------------------------------------------------------------
//  /HiperTools/Table.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30.Table / HiperTools30.TableStyle
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

// Style.BorderFormat:
// ------------------------------------------------------
var tbBdFormatCompleteGrid = 0;    //Grade completa
var tbBdFormatOnlyLines = 1;       //Apenas linhas
var tbBdFormatOutterGridLines = 2; //Grade externa + linhas
var tbBdFormatInvisible = 3;       //Sem grade

// HiperTools30.Table.Style.ColorFormat:
// ------------------------------------------------------
var tbStFormatHeader = 0;                  //Cabecalho cor 1, resto cor 2
var tbStFormatHeaderAlternateColumns = 1;  //Alterna colunas
var tbStFormatAlternateColumns = 2;        //Cabecalho fixo, alterna colunas
var tbStFormatHearderAlternateLines = 3;   //Alterna linhas
var tbStFormatAlternateLines = 4;          //Cabecalho fixo, alterna linhas
var tbStFormatNothing = 5;                 //Todo da cor 1(menos o Título)
var tbStFormatTitle = 6;                   //Todo da cor 1(inclusive Título)
%>





