<%
// -------------------------------------------------------------------------
//  /HiperTools/Validate.inc
// -------------------------------------------------------------------------
//  Descricao  : Constantes do HiperTools30.Validate
//  Criação    : 19/02/2000 11:21AM
//  Local      : Brasilia/DF
//  Elaborado  : Ruben Zevallos <ruben@zevallos.com.br>
//               Fernando Aquino <fernando@zevallos.com.br>
//               Kelson Medeiros <kelson@zevallos.com.br>
//               Ueslei Silva <ueslei@zevallos.com.br>
//               Eduardo Silva <ueslei@zevallos.com.br>
//               Ridai Govinda <ridai@zevallos.com.br>
//  Copyright  : 2000 by Zevallos(r) Tecnologia em Informacao
// -------------------------------------------------------------------------

// Precedência de validação de CPF ou CGC
// ---------------------------------------
var vlCpCPFFirst = 0;
var vlCpCGCFirst = 1;

// Valores de Retorno do Validate.CompareDate
// ---------------------------------------
var vlCmpDateFirstInvalid = 1;
var vlCmpDateSecondInvalid = 2;
var vlCmpDateBothInvalid = 3;
var vlCmpDateOutOfRange = 4;

%>