<%
REM =========================================================================
REM  /Constants.inc
REM -------------------------------------------------------------------------
REM Nome     : Constates do sistema ZEUS III
REM Descricao: Menu para o Sistema ZEUS III
REM Home     : http://www.hipertools.com.br/
REM Criacao  : 2/12/0 5:14PM
REM Autor    : Zevallos Tecnologia em Informacao
REM Versao   : 1.1.0.0
REM Local    : Brasília - DF
REM Companhia: 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

  Const conWhatEmpresa = "1"
  Const conWhatSistema = "2"
  Const conWhatTabela  = "3"
  Const conWhatCampo   = "4"

  Const conListEmpresaUF = "101"

  Const conListCampoTipo          = "141"
  Const conListCampoDelimitador   = "142"

  ' Constantes do sistema
  Const conAspas             = """"
  Const conScriptTimeout     = 15
  Const conSessionTimeout    = 300
  Const conConnectionTimeout = 300
  Const conCommandTimeout    = 300
  Const conSelectAll         = "SELECT * FROM "
  Const conTotalBlocks       = "/8 - "
  Const conToMakeSystem      = "MS"
  Const conOptions           = "O"
  Const conImportCompany     = "C"
  Const conImportSystem      = "S"
  Const conImportConnection  = "ImportConnection"
  Const conOptionInitImport  = "1"
  Const conOptionTable       = "2"
  Const conOptionRename      = "3"
  Const conOptionImport      = "4"




REM -------------------------------------------------------------------------
REM Fim do Constants.inc
REM =========================================================================
%>