<%
REM =========================================================================
REM  /Constants.inc
REM -------------------------------------------------------------------------
REM  Descricao   : Constantes do sistema
REM  Criaзгo     : 2000/04/27 12:18AM
REM  Local       : Brasнlia/DF
REM  Elaborado   : Kelson da Costa Medeiros
REM  Versao      : 1.0.0
REM  Copyright   : 1999 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

  ' QueryStrings
  Const conQSOption = "O"

  ' Genйricas
  Const sstrSN            = "Sugestions.asp"
  Const conScriptTimeout  = 30
  Const conSessionTimeout = 300

  ' EditForm
  Const conWhatSugest    = "1"
  Const conWhatBugs      = "2"
  Const conWhatClasses   = "3"
  Const conWhatPosition  = "4"
  Const conWhatIdeias    = "5"
  Const conWhatMelhorias = "6"
  Const conWhatPessoas   = "7"

%>