<%
REM =========================================================================
REM  /Constants.inc
REM -------------------------------------------------------------------------
REM Nome     : Constates do sistema ZEUS III
REM Descricao: Menu para o Sistema ZEUS III
REM Home     : http://www.hipertools.com.br/
REM Criacao  : 2/12/0 5:14PM
REM Autor    : Zevallos Tecnologia em Informacao
REM Versao   : 1.1.0.0
REM Local    : Brasília - DF
REM Companhia: 2000 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------

  Const conWhatChamaTecnico = "1"

  Const conListSetor     = "10"
  Const conListUsuario   = "11"
  Const conListTempo     = "12"
  Const conListAtendente = "13"
  Const conListProblema  = "14"

  Const conTypeHardware = "1"
  Const conTypeSoftware = "2"
  Const conTypeMicroinf = "3"

  Const conNumColumns = "3"

  Const conScriptTimeout  = 15
  Const conSessionTimeout = 300

REM -------------------------------------------------------------------------
REM Fim do Constants.inc
REM =========================================================================
%>